### ISSUE TITLE
save community as pdf

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#176]
per feedback from MI. We were already planning on having this, so opening it up as an issue.

PDF should have

- drawn map on mapbox streets background
- public information about interests clearly displayed
- anything else? census blocks/counties/state legislature lines?

**Comment by indraneel** [comment]
This was good feedback and I'm glad to see an issue already opened up

- I'm in favor of county/state leg lines, as it might help map-drawers contextualize the data — but I feel like it may be out of scope for an initial release because I can imagine it's a bit tricky to get right?
- We can probably include the campaign/organization name, though less prominently than other information - I think that has relevance
- I'm not sure if we should include Representable branding - I do worry that it might needlessly bias the data, but on the other hand it might be helpful if we do end up building a relationship with state commissions. I would say we can leave it out for now and revisit later.
