### ISSUE TITLE
Some users report that bigger maps don't highlight all the census blocks.

### ISSUE THREAD

**Issue by theodormarcu** [Representable/representable#261]
**Describe the bug**
Bigger user polygons don't highlight the right number of census blocks.

**To Reproduce**
I could not replicate the issue. The issue seems to be related to polygons that have a lot of points.

**Expected behavior**
All maps should display the right number of polygons.

**Screenshots**
<img width="649" alt="Screen_Shot_2020-06-25_at_10 50 08" src="https://user-images.githubusercontent.com/8714338/86176587-293e7600-baf3-11ea-8bb4-787c3b22eef1.png">

**Comment by k-y-le** [comment]
Following up to say that this is still a problem with block groups -- the smallest block groups (which are just city blocks in urban areas) do not highlight when at a very low zoom. One possible solution is to set a min zoom on the map so that users aren't allowed to get that far out.

Here's a screenshot of the zoom level in which block groups will no longer be highlighted when selecting the polygon. Any closer and it will query and highlight all block groups :: it's pretty far out so i don't know that it would be a big detriment to UX to institute a min zoom
![image](https://user-images.githubusercontent.com/41943646/87271696-5dfcf500-c517-11ea-8bd8-a59ae6abd674.png)

**Comment by lauren-johnston** [comment]
Closing given shift to block groups.
