### ISSUE TITLE
Bug: Cookie settings displays duplicate text on dashboard

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#298]
**Describe the bug**
See screenshot.

**To Reproduce**
1. opt-in on one window
2. Then go incognito and opt-out

**Expected behavior**

**Screenshots**
<img width="1145" alt="Screen Shot 2020-07-15 at 7 42 35 PM" src="https://user-images.githubusercontent.com/8892509/87620488-8fbabb00-c6d3-11ea-84e6-093387deaad4.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lauren-johnston** [comment]
@theodormarcu just noticed this - not a huge deal but figured I'd open a bug report

**Comment by theodormarcu** [comment]
Good catch! To reiterate, cookie settings are not saved on the server. Every time you go on a new browser/incognito, you will be shown the banner/option. The "Opt In"/"Opt Out" buttons should definitely not appear together, though, so I'll look into that part of the issue.

Until we save cookie settings for logged in users on the server, we won't be able to save a cookie state for a logged in user. I tried doing a toy implementation, but I got stuck on updating the DB model without a form. I'll see if I can do something quickly, but payoff is pretty minimal because it would only impact logged in users, who will probably only access representable from their primary device.

Thanks for looking into this!

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

**Comment by lauren-johnston** [comment]
Thanks yeah if you could look into this that would be great!

Also v minor, noticed this link in the footer is just an empty "#" link

<img width="296" alt="Screen Shot 2020-07-16 at 10 26 17 AM" src="https://user-images.githubusercontent.com/8892509/87702874-d5689980-c74e-11ea-89ff-e6534e9ced7c.png">

**Comment by theodormarcu** [comment]
The link is empty because the action is onClick() rather than a link.

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

**Comment by lauren-johnston** [comment]
> The link is empty because the action is onClick() rather than a link. *Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

Hmm... the link/action doesn't do anything for me.

**Comment by lauren-johnston** [comment]
@theodormarcu btw this is the error im getting: <img width="484" alt="Screen Shot 2020-07-24 at 3 20 25 PM" src="https://user-images.githubusercontent.com/8892509/88439893-464c2900-cdc1-11ea-8246-f56050c247fa.png">
