### ISSUE TITLE
Entry page map zooms in too far on certain zipcodes

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#44]
Issue replicated locally for 08544 zipcode: 

<img width="885" alt="Screen Shot 2020-05-05 at 10 47 25 PM" src="https://user-images.githubusercontent.com/8892509/81141740-6686ed00-8f22-11ea-92d7-c172c727061b.png">

Adding this here so we can keep track of issues!

**Comment by theodormarcu** [comment]
Had a conversation with Somya about this. We couldn't find any setting in Mapbox to prevent this. This happens very rarely, only for select zipcodes that are very small because of their special status, like Princeton University's own zipcode. I am not sure we can do anything JS-wise to prevent this.
